version: '2'

services:
  web:
    image: 994642778742.dkr.ecr.us-east-1.amazonaws.com/dallasphpbot/nginx:latest
    volumes_from:
      - app
    ports:
      - 80:80
  fpm:
    image: php:7.2-fpm
    volumes_from:
      - app
    ports:
      - 9000:9000
    environment:
      - SLACK_TOKEN
  app:
    image: 994642778742.dkr.ecr.us-east-1.amazonaws.com/tardibot:latest
